steps:
  - name: "docker"
    args:
      [
        "buildx",
        "create",
        "--driver",
        "docker-container",
        "--name",
        "container",
        "--use",
      ]
  - name: "docker"
    args:
      [
        "buildx",
        "build",
        "--platform",
        "linux/amd64",
        "-t",
        "us-east1-docker.pkg.dev/hatakeyamallm/cloud-run-commoncrawl:latest",
        "--push",
        ".",
      ]
